/////////////////////////////////////////////////////////////////////////////
// Name:        aboutdlg.cpp
// Purpose:     
// Author:      Jarle Aase
// Modified by: 
// Created:     01/01/2007 10:54:53
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "aboutdlg.h"
#endif

#include "libwhid.h"
#include "WhidApp.h"
#include <WarUtf8.h>
#include <WarCollector.h>

#ifdef WIN32
#   include <shellapi.h>
#endif


// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "AboutDlg.h"

////@begin XPM images
////@end XPM images

/*!
 * AboutDlg type definition
 */

IMPLEMENT_DYNAMIC_CLASS( AboutDlg, wxDialog )

/*!
 * AboutDlg event table definition
 */

BEGIN_EVENT_TABLE( AboutDlg, wxDialog )

////@begin AboutDlg event table entries
    EVT_BUTTON( ID_HOMEPAGE, AboutDlg::OnHOMEPAGEClick )

    EVT_BUTTON( ID_DONATE, AboutDlg::OnDONATEClick )

////@end AboutDlg event table entries

END_EVENT_TABLE()

/*!
 * AboutDlg constructors
 */

AboutDlg::AboutDlg( )
{
    Init();
}

AboutDlg::AboutDlg( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}

/*!
 * AboutDlg creator
 */

bool AboutDlg::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin AboutDlg creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end AboutDlg creation
    return true;
}

/*!
 * Member initialisation 
 */

void AboutDlg::Init()
{
////@begin AboutDlg member initialisation
    mHtmlCtl = NULL;
////@end AboutDlg member initialisation
}
/*!
 * Control creation for AboutDlg
 */

void AboutDlg::CreateControls()
{    
////@begin AboutDlg content construction
    // Generated by DialogBlocks, fr. 23. jan. 2009 kl. 09.19 +0200 (unregistered)

    AboutDlg* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxStaticBitmap* itemStaticBitmap3 = new wxStaticBitmap( itemDialog1, wxID_STATIC, itemDialog1->GetBitmapResource(wxT("icons/other/about_scaled.png")), wxDefaultPosition, wxSize(400, 265), 0 );
    itemBoxSizer2->Add(itemStaticBitmap3, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    mHtmlCtl = new WhidHtmlWindow( itemDialog1, ID_ABOUT_HTML, wxDefaultPosition, wxSize(400, 80), wxHW_SCROLLBAR_AUTO|wxNO_BORDER );
    itemBoxSizer2->Add(mHtmlCtl, 0, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer5 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer5, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxButton* itemButton6 = new wxButton( itemDialog1, ID_HOMEPAGE, _("Homepage"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer5->Add(itemButton6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton7 = new wxButton( itemDialog1, ID_DONATE, _("Donate"), wxDefaultPosition, wxDefaultSize, 0 );
    itemButton7->Show(false);
    itemBoxSizer5->Add(itemButton7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton8 = new wxButton( itemDialog1, wxID_OK, _("&Close"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer2->Add(itemButton8, 0, wxGROW|wxALL, 5);

////@end AboutDlg content construction

    // Create custom windows not generated automatically here.
////@begin AboutDlg content initialisation
////@end AboutDlg content initialisation

    WarCollector<wchar_t> html;

    html << "<html><body bgimage=\"icons/other/about_scaled.png\">";

    html << "<font size=2 face=arial><p align=center><b>" 
        << PROGRAM
        << "</b> " 
        << _("version") 
        << " " 
        << WHID_VERSION
        << "<br>"
        << COPYRIGHT 
        << "</p>";

    html << "<p> <a href=\"http://whid.jgaa.com\">" 
        << PROGRAM 
        << "</a> "
        << _("is free software (as in free), published under the")
        << " "
        << "<a href=\"http://www.fsf.org\">GNU Public License version 3"
        << "</a>. "
        << _("There are no nags, no banners, no adware, no spyware.") 
        << " "
        << _("The source-code is available for download from sourceforge.net") 
        << "</p>";

    html << "<p>" 
        << PROGRAM 
        << " " 
        << _("is written by") 
        << " "
        << "<a href=\"http://www.jgaa.com\">Jarle Aase</a> "
        << _("from Norway.") 
        << " "
        << _("Jarle has released free software since 1985.")
        << "</p>";


    html << "</body></html>";

    mHtmlCtl->SetPage(html.GetValue().c_str());
}

/*!
 * Should we show tooltips?
 */

bool AboutDlg::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap AboutDlg::GetBitmapResource( const wxString& name )
{
    return WhidApp::GetBitmapResource( name );
    // Bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon AboutDlg::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin AboutDlg icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end AboutDlg icon retrieval
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_HOMEPAGE
 */

void AboutDlg::OnHOMEPAGEClick( wxCommandEvent& event )
{
    BROWSER(_("http://whid.jgaa.com"));
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_DONATE
 */

void AboutDlg::OnDONATEClick( wxCommandEvent& event )
{
    BROWSER(_("http://donate.jgaa.com"));
}

