#!groovy

env.WHID_VERSION="2.0.1"

pipeline {
    agent { label 'master' }

    stages {
        stage('Build') {
            parallel {
                stage('Docker-build inside: Ubuntu-xenial') {
                    agent {
                        dockerfile {
                            filename 'Dockefile.ubuntu-xenial'
                            dir 'ci/jenkins'
                            label 'master'
                        }
                    }

                    steps {
                        echo "Building on ubuntu-xenial-AMD64 in ${WORKSPACE}"
                        checkout scm
                        withEnv(["DIST_DIR=${WORKSPACE}/dist", "BUILD_DIR=${WORKSPACE}/build", "SRC_DIR=${WORKSPACE}"]) {
                            sh 'pwd; ls -la;'
                            sh './scripts/package-deb.sh'
                        }
                    }

                    post {
                        success {
                            echo "Build of debian package suceeded!"
                            archive "**/whid*.deb"
                        }
                    }
                }
            }
        }
    }
}
